### PR TITLE
java8mig-728: getting repo information from parameters

### PR DESCRIPTION
**Pull request by apgsga-jhe**
As soon as merged on master, a new pull request in order to merge master on 1.1.x will also be done to push the modification on prod branch.
All properties which have been added already exist in gradle.properties file.

### CODE REVIEW

**Comment by chhex** [comment]
@apgsga-jhe  yep, fine.

**Comment by apgsga-jhe** [comment]
@chhex : 

> @apgsga-jhe yep, fine. Btw , you could also make a pull request from 1.1.x branch, merge that one and back port the change to master.

You mean:

1. I change this pull request in order to merge java8mig728 into 1.1.x
2. I do the merge.
3. I create a new pull request to merge 1.1.x into master

Or does Github have any mechanism for backporting commit? I had a look but didn't found any built-in functionnality.

**Comment by apgsga-jhe** [comment]
@chhex : that would actually be a rebase of master, isn't it?

**Comment by apgsga-jhe** [comment]
@chhex : to summarize, I could:

1. Closee this Pull Request without doing anything.
2. Create a new Pull request from java8mig728 to 1.1.x
3. "Merge and Rebase" this new pull request.

Then, "Master" should be rebased with the last commit... Maybe we can try once together?

**Pull request merged**
